In [12]:
# CELL 1 — load the updated functions and enter your accession and ID
import importlib
import d_pride_lfq_functions_proteins as lfq
importlib.reload(lfq)

DATASET = {
    "accession": "PXD052763",
    "ID": "M1002",  # Enter your own dataset ID, for example H1001.
}

In [13]:
# CELL 2 — download/cache the tables and inspect the numbered LFQ columns

downloaded_tables, lfq_catalog = lfq.prepare_lfq_selection(DATASET)

  Skipped ZIP member proteinGroups.txt: That compression method is not supported
  Skipped ZIP member proteinGroups.txt: That compression method is not supported
M1002 / PXD052763: 5 table(s), 38 LFQ columns.
Table ID -> URL:

  table_id                                                URL
0  table_1  https://ftp.pride.ebi.ac.uk/pride/data/archive...
1  table_2  https://ftp.pride.ebi.ac.uk/pride/data/archive...
2  table_3  https://ftp.pride.ebi.ac.uk/pride/data/archive...
3  table_4  https://ftp.pride.ebi.ac.uk/pride/data/archive...
4  table_5  https://ftp.pride.ebi.ac.uk/pride/data/archive...

Select by row_number (1-based). Similar labels from all tables are shown together.

            sample_name table_id            LFQ_column_name
row_number
1            BRF41Con_1  table_1   LFQ intensity BRF41Con_1
2            BRF41Con_2  table_1   LFQ intensity BRF41Con_2
3            BRF41Con_3  table_1   LFQ intensity BRF41Con_3
4            BRF41Con_4  table_1   LFQ intensity BRF41Con_4
5           BRF41Telo_1  table_1  LFQ intensity BRF41Telo_1
6           BRF41Telo_2  table_1  LFQ intensity BRF41Telo_2
7           BRF41Telo_3  table_1  LFQ intensity BRF41Telo_3
8           BRF41Telo_4  table_1  LFQ intensity BRF41Telo_4
9                  MT_1  table_5         LFQ intensity MT_1
10                 MT_2  table_5         LFQ intensity MT_2
11                 MT_3  table_5         LFQ intensity MT_3
12                 MT_4  table_5         LFQ intensity MT_4
13                 WT_1  table_2         LFQ intensity WT_1
14                 WT_1  table_3         LFQ intensity WT_1
15                 WT_1  table_4         LFQ intensity WT_1
16                 WT_1  table_5         LFQ intensity WT_1
17                 WT_2  table_2         LFQ intensity WT_2
18                 WT_2  table_3         LFQ intensity WT_2
19                 WT_2  table_4         LFQ intensity WT_2
20                 WT_2  table_5         LFQ intensity WT_2
21                 WT_3  table_2         LFQ intensity WT_3
22                 WT_3  table_3         LFQ intensity WT_3
23                 WT_3  table_4         LFQ intensity WT_3
24                 WT_3  table_5         LFQ intensity WT_3
25                 WT_4  table_2         LFQ intensity WT_4
26                 WT_4  table_4         LFQ intensity WT_4
27                 WT_4  table_5         LFQ intensity WT_4
28                zMT_1  table_2        LFQ intensity zMT_1
29                zMT_1  table_3        LFQ intensity zMT_1
30                zMT_1  table_4        LFQ intensity zMT_1
31                zMT_2  table_2        LFQ intensity zMT_2
32                zMT_2  table_3        LFQ intensity zMT_2
33                zMT_2  table_4        LFQ intensity zMT_2
34                zMT_3  table_2        LFQ intensity zMT_3
35                zMT_3  table_3        LFQ intensity zMT_3
36                zMT_3  table_4        LFQ intensity zMT_3
37                zMT_4  table_2        LFQ intensity zMT_4
38                zMT_4  table_4        LFQ intensity zMT_4

In [14]:
# CELL 3 — define your group names and inclusive row-number ranges
GROUPS = {
    # Experiment 1 — Control
"MT_6c_Testes10_5monthproteome": [9, 12], "WT_6c_Testes10_5monthproteome": [[16, 16], [20, 20], [24, 24], [27, 27]], "WT_6a_Ovaries40dpf": [[14, 14], [18, 18], [22, 22]], "zMT_6a_Ovaries40dpf": [[29, 29], [32, 32], [35, 35]], "WT_6b_Testes40dpf": [[15, 15], [19, 19], [23, 23], [26, 26]], "zMT_6b_Testes40dpf": [[30, 30], [33, 33], [36, 36], [38, 38]] }
grouping_preview = lfq.preview_lfq_range_groups(GROUPS, lfq_catalog)
print(", ".join(f'"{group_name}": {ranges}' for group_name, ranges in GROUPS.items()))

,group,row_numbers,n_LFQ_columns,tables,LFQ_columns
0,MT_6c_Testes10_5monthproteome,"[9, 10, 11, 12]",4,table_5,9: LFQ intensity MT_1 (table_5); 10: LFQ intensity MT_2 (table_5); 11: LFQ intensity MT_3 (table_5); 12: LFQ intensity MT_4 (table_5)
1,WT_6c_Testes10_5monthproteome,"[16, 20, 24, 27]",4,table_5,16: LFQ intensity WT_1 (table_5); 20: LFQ intensity WT_2 (table_5); 24: LFQ intensity WT_3 (table_5); 27: LFQ intensity WT_4 (table_5)
2,WT_6a_Ovaries40dpf,"[14, 18, 22]",3,table_3,14: LFQ intensity WT_1 (table_3); 18: LFQ intensity WT_2 (table_3); 22: LFQ intensity WT_3 (table_3)
3,zMT_6a_Ovaries40dpf,"[29, 32, 35]",3,table_3,29: LFQ intensity zMT_1 (table_3); 32: LFQ intensity zMT_2 (table_3); 35: LFQ intensity zMT_3 (table_3)
4,WT_6b_Testes40dpf,"[15, 19, 23, 26]",4,table_4,15: LFQ intensity WT_1 (table_4); 19: LFQ intensity WT_2 (table_4); 23: LFQ intensity WT_3 (table_4); 26: LFQ intensity WT_4 (table_4)
5,zMT_6b_Testes40dpf,"[30, 33, 36, 38]",4,table_4,30: LFQ intensity zMT_1 (table_4); 33: LFQ intensity zMT_2 (table_4); 36: LFQ intensity zMT_3 (table_4); 38: LFQ intensity zMT_4 (table_4)

Selected 22 of 38 LFQ columns in 6 group(s).
"MT_6c_Testes10_5monthproteome": [9, 12], "WT_6c_Testes10_5monthproteome": [[16, 16], [20, 20], [24, 24], [27, 27]], "WT_6a_Ovaries40dpf": [[14, 14], [18, 18], [22, 22]], "zMT_6a_Ovaries40dpf": [[29, 29], [32, 32], [35, 35]], "WT_6b_Testes40dpf": [[15, 15], [19, 19], [23, 23], [26, 26]], "zMT_6b_Testes40dpf": [[30, 30], [33, 33], [36, 36], [38, 38]]

In [26]:
# CELL 4 — aggregate LFQ columns within each original row and save the report
SETTINGS = {
    "group_aggregation": "mean",  # Options: median, mean, min, max, sum.
    "presence_threshold": 0.10,     # Strict >10% across ALL LFQ columns in each source table.
    "treat_zero_as_missing": False, # Include zeros when aggregating qualifying rows.
    "append_to_existing": False,    # Add groups to an existing protein-row report.
    "report_file": f"{DATASET['ID']}_{DATASET['accession']}_try2.csv",
}

result = lfq.process_lfq_ranges_and_show(
    DATASET, GROUPS, SETTINGS, downloaded_tables, lfq_catalog
)

Reports saved to:
  table_1: /Users/mehman/Projects/proteomics_analysis/M1002_PXD077620_try2_table_1.csv
  table_2: /Users/mehman/Projects/proteomics_analysis/M1002_PXD077620_try2_table_2.csv

Source rows and whole-table presence:

,table_id,source_rows,rows_passing_presence,rows_failing_presence,selected_LFQ_columns,whole_table_LFQ_columns,presence_rule
0,table_1,6124,6103,21,15,15,Presence > 0.1
1,table_2,7049,7026,23,8,8,Presence > 0.1

Group representatives:

,group,row_numbers,tables,LFQ_columns,aggregation,protein_rows_with_values,output_column
0,WT_Untreated,"[1, 3, 7, 11, 13]",table_1,5,mean,6103,M1002_PXD077620_WT_Untreated
1,KI_AAV_Control,"[2, 4, 6, 10, 14]",table_1,5,mean,6103,M1002_PXD077620_KI_AAV_Control
2,KI_AAV_ALPK3,"[5, 8, 9, 12, 15]",table_1,5,mean,6103,M1002_PXD077620_KI_AAV_ALPK3
3,TTNtv_AAV_ALPK3,"[16, 17, 18, 19]",table_2,4,mean,7026,M1002_PXD077620_TTNtv_AAV_ALPK3
4,TTNtv_AAV_Control,"[20, 21, 22, 23]",table_2,4,mean,7026,M1002_PXD077620_TTNtv_AAV_Control

Report previews:

table_1:

,Protein IDs,Majority protein IDs,Protein names,Gene names,Fasta headers,Only identified by site,Reverse,Potential contaminant,Source file,Source row,M1002_PXD077620_WT_Untreated,M1002_PXD077620_KI_AAV_Control,M1002_PXD077620_KI_AAV_ALPK3
0,A0A023T778;Q9CQL1;P61327;G3UZW7,A0A023T778;Q9CQL1;P61327;G3UZW7,Protein mago nashi homolog 2;Protein mago nash...,Magohb;Magoh,"tr|A0A023T778|A0A023T778_MOUSE Mago homolog B,...",,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,1,12033800.0,11999440.0,12470800.0
1,A0A024QYR9;O08586,A0A024QYR9;O08586,"Phosphatidylinositol 3,4,5-trisphosphate 3-pho...",Pten,tr|A0A024QYR9|A0A024QYR9_MOUSE Phosphatidylino...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,2,597280.0,490984.0,555148.0
2,A0A067XG51;B1AU22;B1AU23,A0A067XG51;B1AU22;B1AU23,,Fgf13,tr|A0A067XG51|A0A067XG51_MOUSE Fibroblast grow...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,3,312508.0,249892.0,285000.0
3,A0A075B5K0;A0A140T8P9;P01638;P01637,A0A075B5K0;A0A140T8P9;P01638;P01637,Ig kappa chain V-V region L6;Ig kappa chain V-...,Igkv14-126;Igkv14-111,tr|A0A075B5K0|A0A075B5K0_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,4,2204650.0,859206.0,1593700.0
4,A0A075B5K2;A0A0G2JDR3,A0A075B5K2;A0A0G2JDR3,,Igkv9-124,tr|A0A075B5K2|A0A075B5K2_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,5,1278530.0,1077342.0,1839998.0
5,A0A075B5K6;P03976,A0A075B5K6;P03976,Ig kappa chain V-II region 17S29.1,Igkv2-109,tr|A0A075B5K6|A0A075B5K6_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,6,698150.0,187066.36,186091.4
6,A0A075B5M2;A0A075B5M3;A0A0G2JH00;A0A0G2JGI6;A0...,A0A075B5M2;A0A075B5M3;A0A0G2JH00;A0A0G2JGI6;A0...,Ig kappa chain V-IV region S107B,Igkv4-61;Igkv4-58;Igkv4-91,tr|A0A075B5M2|A0A075B5M2_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,7,1774406.0,411400.0,893700.0
7,A0A075B5M1;A0A0G2JFU6,A0A075B5M1;A0A0G2JFU6,,Igkv4-63,tr|A0A075B5M1|A0A075B5M1_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,8,171508.2,146216.4,155878.4
8,A0A075B5M7;A0A0G2JDV4;A0A0B4J1J2;A0A0B4J1J1,A0A075B5M7;A0A0G2JDV4,,Igkv5-39,tr|A0A075B5M7|A0A075B5M7_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,9,1903620.0,3442780.0,2478920.0
9,A0A075B5N3;A0A0G2JE47,A0A075B5N3;A0A0G2JE47,,Igkv8-28,tr|A0A075B5N3|A0A075B5N3_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,10,5025880.0,3697940.0,6860220.0
10,A0A075B5N4;A0A0G2JF28,A0A075B5N4;A0A0G2JF28,,Igkv8-27,tr|A0A075B5N4|A0A075B5N4_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,11,434580.0,250242.0,277363.2
11,A0A075B5N9;A0A0G2JE31;P01674;P01673;P01657;P01659,A0A075B5N9;A0A0G2JE31;P01674,Ig kappa chain V-III region PC 2154,Igkv3-7,tr|A0A075B5N9|A0A075B5N9_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,12,12861280.0,25130580.0,10527500.0
12,A0A075B5P1,A0A075B5P1,,Igkv3-1,tr|A0A075B5P1|A0A075B5P1_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,13,159139.4,416732.4,84429.6
13,A0A075B5P3;A0A0A6YVP0;P01867;P01863;P01865,A0A075B5P3;A0A0A6YVP0;P01867,Immunoglobulin heavy constant gamma 2B,Ighg2b,tr|A0A075B5P3|A0A075B5P3_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,14,78575400.0,63056000.0,68884000.0
14,A0A075B5P4;A0A0A6YWR2;P01868;P01869,A0A075B5P4;A0A0A6YWR2;P01868;P01869,Ig gamma-1 chain C region secreted form;Ig gam...,Ighg1,tr|A0A075B5P4|A0A075B5P4_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,15,11992820.0,8528360.0,8845100.0
15,A0A075B5P5;A0A1Y7VJN6;P03987,A0A075B5P5;A0A1Y7VJN6;P03987,Ig gamma-3 chain C region,Ighg3,tr|A0A075B5P5|A0A075B5P5_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,16,9260480.0,4496240.0,6834400.0
16,A0A075B6A0;A0A075B5P6;P01872,A0A075B6A0;A0A075B5P6;P01872,Immunoglobulin heavy constant mu;Mu chain,Ighm,tr|A0A075B6A0|A0A075B6A0_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,17,12893800.0,11935300.0,20148400.0
17,A0A075B5P9;P18527;A0A0A6YVS4,A0A075B5P9;P18527,Ig heavy chain V region 914,Ighv5-4,tr|A0A075B5P9|A0A075B5P9_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,18,473450.0,132076.0,179825.0
18,A0A075B5Q3;A0A0A6YY69;A0A075B5Q1,A0A075B5Q3;A0A0A6YY69,,Ighv2-5,tr|A0A075B5Q3|A0A075B5Q3_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,19,427434.0,658276.0,220822.0
19,A0A075B5R0;A0A0B4J1P4,A0A075B5R0;A0A0B4J1P4,,Ighv5-16,tr|A0A075B5R0|A0A075B5R0_MOUSE Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,20,20307880.0,9909920.0,13435780.0

table_2:

,Protein IDs,Majority protein IDs,Protein names,Gene names,Fasta headers,Only identified by site,Reverse,Potential contaminant,Source file,Source row,M1002_PXD077620_TTNtv_AAV_ALPK3,M1002_PXD077620_TTNtv_AAV_Control
0,A0A024QZX5;A0A087X1N8;P35237;A0A2R8YD12;A0A2R8...,A0A024QZX5;A0A087X1N8;P35237;A0A2R8YD12,Serpin B6,SERPINB6,tr|A0A024QZX5|A0A024QZX5_HUMAN Serpin B6 OS=Ho...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,1,7179450.0,9959600.0
1,F2Z3D1;J3QR79;A0A024R161;Q9H1X3-3;Q9H1X3,F2Z3D1;J3QR79;A0A024R161;Q9H1X3-3;Q9H1X3,DnaJ homolog subfamily C member 25;Guanine nuc...,DNAJC25;DNAJC25-GNG10,tr|F2Z3D1|F2Z3D1_HUMAN DnaJ homolog subfamily ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,2,27477.0,27897.5
2,Q00341;A0A024R4E5;Q00341-2;H0Y394;H7C0A4;C9JIZ...,Q00341;A0A024R4E5;Q00341-2;H0Y394,Vigilin,HDLBP,sp|Q00341|VIGLN_HUMAN Vigilin OS=Homo sapiens ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,3,48961000.0,42881250.0
3,A0A087WZA9;A0A024R4K9;A0A087X266;Q9BXJ8-2;Q9BXJ8,A0A087WZA9;A0A024R4K9;A0A087X266;Q9BXJ8-2;Q9BXJ8,Ion channel TACAN,TMEM120A,tr|A0A087WZA9|A0A087WZA9_HUMAN Ion channel TAC...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,4,37158.0,27595.5
4,A0A024R571;Q9H4M9;C9JC03;C9J2Z4;C9JDQ8;C9JIJ3;...,A0A024R571;Q9H4M9;C9JC03;C9J2Z4,EH domain-containing protein 1,EHD1,tr|A0A024R571|A0A024R571_HUMAN EH domain conta...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,5,5601350.0,5918275.0
5,A0A024R5G9;A0A7I2V4A8;A0A7I2V5B9;A0A7I2V3M3;A0...,A0A024R5G9;A0A7I2V4A8;A0A7I2V5B9;A0A7I2V3M3;A0...,Cathepsin F,CTSF,tr|A0A024R5G9|A0A024R5G9_HUMAN Cathepsin F OS=...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,6,8960375.0,11778900.0
6,A0A024R6N5;P01009;A0A0G2JRN3;P01009-2;P01009-3...,A0A024R6N5;P01009;A0A0G2JRN3;P01009-2,Alpha-1-antitrypsin;Short peptide from AAT,SERPINA1,tr|A0A024R6N5|A0A024R6N5_HUMAN Serpin family A...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,7,1138775.0,877517.5
7,K7EN05;K7EPC8;A0A024R7E8;K7EQ44;K7EMV4;P60002,K7EN05;K7EPC8;A0A024R7E8;K7EQ44;K7EMV4;P60002,Transcription elongation factor 1 homolog,ELOF1,tr|K7EN05|K7EN05_HUMAN Transcription elongatio...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,8,415067.5,650085.0
8,A0A024R7P0;O14593-2;O14593-3;O14593;H0YGQ6;F5G...,A0A024R7P0;O14593-2;O14593-3;O14593;H0YGQ6;F5GY33,DNA-binding protein RFXANK,RFXANK,tr|A0A024R7P0|A0A024R7P0_HUMAN Regulatory fact...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,9,144262.5,122842.0
9,A0A024R7W5;A0A087X0Q1;A0A087WY31;Q7Z739,A0A024R7W5;A0A087X0Q1;A0A087WY31;Q7Z739,YTH domain-containing family protein;YTH domai...,YTHDF3,tr|A0A024R7W5|A0A024R7W5_HUMAN YTH domain-cont...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,10,1854375.0,1910550.0
10,A0A024RA52;P25787;A0A7I2V2H3;A0A7I2YQP7;C9JCK5...,A0A024RA52;P25787;A0A7I2V2H3;A0A7I2YQP7;C9JCK5,Proteasome subunit alpha type;Proteasome subun...,PSMA2,tr|A0A024RA52|A0A024RA52_HUMAN Proteasome subu...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,11,13917750.0,15777250.0
11,A0A024RBG1;Q9NZJ9-2;Q9NZJ9-3,A0A024RBG1;Q9NZJ9-2;Q9NZJ9-3,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B;NUDT4,sp|A0A024RBG1|NUD4B_HUMAN Diphosphoinositol po...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,12,556090.0,640357.5
12,E9PRM7;A0A0J9YWM3;A0A024RCG2;Q96BI1,E9PRM7;A0A0J9YWM3;A0A024RCG2;Q96BI1,Solute carrier family 22 member 18,SLC22A18,tr|E9PRM7|E9PRM7_HUMAN Solute carrier family 2...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,13,127542.25,62006.5
13,P46379-3;P46379;P46379-2;A0A7I2V508;A0A0G2JK23...,P46379-3;P46379;P46379-2;A0A7I2V508;A0A0G2JK23...,Large proline-rich protein BAG6,BAG6,sp|P46379-3|BAG6_HUMAN Isoform 3 of Large prol...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,14,1600275.0,1514800.0
14,G8JLL2;A0A0G2JK02;A0A0G2JIU6;A0A0G2JHB6;A0A0G2...,G8JLL2;A0A0G2JK02;A0A0G2JIU6;A0A0G2JHB6;A0A0G2...,Lysosomal thioesterase PPT2,PPT2,tr|G8JLL2|G8JLL2_HUMAN Palmitoyl-protein thioe...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,15,1185197.5,1736600.0
15,A0A075B6F9;Q9Y314;M0R3B2;M0R1K2;M0QX85;M0R1T7;...,A0A075B6F9;Q9Y314;M0R3B2;M0R1K2,Nitric oxide synthase-interacting protein,NOSIP,tr|A0A075B6F9|A0A075B6F9_HUMAN Nitric oxide sy...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,16,2818325.0,2539975.0
16,A0A0C4DH90;P01624;A0A075B6H7;A0A0C4DH55,A0A0C4DH90;P01624;A0A075B6H7;A0A0C4DH55,Immunoglobulin kappa variable 3-15;Probable no...,IGKV3OR2-268;IGKV3-15;IGKV3-7;IGKV3D-7,tr|A0A0C4DH90|A0A0C4DH90_HUMAN Immunoglobulin ...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,17,161242.7,37511.75
17,A0A075B6K5;P80748,A0A075B6K5;P80748,Immunoglobulin lambda variable 3-9;Immunoglobu...,IGLV3-9;IGLV3-21,sp|A0A075B6K5|LV39_HUMAN Immunoglobulin lambda...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,18,23414.65,4189.65
18,A0A087WW49;A0AAG2TU05;P01825;P0DP08;A0A075B6R2...,A0A087WW49;A0AAG2TU05;P01825;P0DP08;A0A075B6R2...,Ig-like domain-containing protein;Immunoglobul...,IGHV4-59;IGHV4-38-2;IGHV4-4;IGHV4-31;IGHV4-30-...,tr|A0A087WW49|A0A087WW49_HUMAN Ig-like domain-...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,19,130483.5,11416.5
19,A2NJV5;A0A0A0MRZ7;A0A075B6S2;A0AAG2T961;A0AAG2...,A2NJV5;A0A0A0MRZ7;A0A075B6S2;A0AAG2T961;A0AAG2...,Immunoglobulin kappa variable 2-29;Immunoglobu...,IGKV2-29;IGKV2D-26;IGKV2D-29;IGKV2-30;IGKV2D-2...,sp|A2NJV5|KV229_HUMAN Immunoglobulin kappa var...,,,,https://ftp.pride.ebi.ac.uk/pride/data/archive...,20,171325.75,342517.0

In [4]:
import ast
import pandas as pd
import d_pride_lfq_functions_proteins as lfq
from pathlib import Path

master = pd.read_excel("b_coverage_reports/dataset_list.xlsx", dtype=str)


for _, row in master.iterrows():

    DATASET = {
        "accession": row["PRIDE_accession"].strip().upper(),
        "ID": row["ID"].strip(),
    }

    rule = row["Rule"].strip()

    GROUPS = ast.literal_eval(
        rule if rule.startswith("{") else f"{{{rule}}}"
    )
    output_folder = Path("c&d_aggrigated_datasets")
    output_folder.mkdir(parents=True, exist_ok=True)
    
    SETTINGS = {
        "group_aggregation": "mean",
        "presence_threshold": 0.10,
        "treat_zero_as_missing": False,
        "append_to_existing": False,
        "report_file": (output_folder/
            f"{DATASET['ID']}_{DATASET['accession']}.csv"
        ),
    }

    try:
        downloaded_tables, raw_catalog = (
            lfq.download_lfq_tables(DATASET["accession"])
        )

        lfq_catalog = lfq.make_numbered_lfq_catalog(
            raw_catalog
        )
        lfq_catalog.attrs.update(DATASET)

        result = lfq.build_range_representative_report(
            dataset=DATASET,
            groups=GROUPS,
            downloaded_tables=downloaded_tables,
            lfq_catalog=lfq_catalog,
            **SETTINGS,
        )

        print(f"✅ {DATASET['ID']} / {DATASET['accession']}")

    except Exception as error:
        print(
            f"⚠️ {DATASET['ID']} / {DATASET['accession']}: "
            f"{type(error).__name__}: {error}"
        )

✅ H1001 / PXD006299

KeyboardInterrupt: